github:
  is_project_page: false
theme: jekyll-theme-slate
title: Open Data on the Web
description: We are a youth run initiative aiming to introduce a data-driven tech culture and make big data more accessible in Pakistan.
